version: '3.8'

services:
  simstudio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://simstudio:simstudio@db:5432/simstudio
      - BETTER_AUTH_SECRET=your-development-secret
      - BETTER_AUTH_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - db
      - realtime
    volumes:
      - simstudio-data:/app/data

  realtime:
    build:
      context: .
      dockerfile: Dockerfile.realtime
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://simstudio:simstudio@db:5432/simstudio
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simstudio
      POSTGRES_USER: simstudio
      POSTGRES_PASSWORD: simstudio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  simstudio-data:
